services:
  cron:
    image: lightyearlabs/lightyear-his:cron-${IMAGE_TAG}
    env_file: ".env"
    volumes:
      - wl:/home/wlVol
  worklist:
    image: lightyearlabs/lightyear-his:worklist-${IMAGE_TAG}
    ports:
      - "3000:3000"
    volumes:
      - wl:/home/wlVol
    depends_on:
      - cron
  store:
    image: lightyearlabs/lightyear-his:store-${IMAGE_TAG}
    ports:
      - "4000:4000"
    volumes:
      - dcm:/home/dcmVol
  uploader:
    image: lightyearlabs/lightyear-his:uploader-${IMAGE_TAG}
    volumes:
      - dcm:/home/dcmVol
    depends_on:
      - store

volumes:
  wl:
  dcm:
